import java.util.Arrays;
class Solution {
    public char findTheDifference(String s, String t) {
        char[] arr = s.toCharArray();
        char[] barr = t.toCharArray();
        Arrays.sort(arr);
        Arrays.sort(barr);
        for (int i = 0; i < arr.length; i++) {
            if (arr[i] != barr[i]) {
                return barr[i]; 
            }
        }
        return barr[barr.length - 1];
    }
}
/*
complexity
Time=>O(n log n)
space=>O(n)
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:
Input: s = "", t = "y"
Output: "y"
*/
